### ISSUE TITLE
Super high CPU usage and temps

### ISSUE THREAD

**Issue by dhaern** [1makarov/binance-nft-buy#11]
I get insane temps and 100% fans speed when I run this latest version:

![image](https://user-images.githubusercontent.com/7317522/132200923-e1fd3716-40d1-497a-a483-01b4e4869e93.png)

My PC build is a Ryzen 5950x and x570-E motherboard. I tried with OC (I get crashes with the overload and very high temps) and OC disabled (no crashes but still very high temps and 100% load).

**Comment by 1makarov** [comment]
perhaps golang is not optimized for such a number of cores, unfortunately I don't know how to fix it :( sorry

**Comment by dhaern** [comment]
Is this relevant to the issue??

![image](https://user-images.githubusercontent.com/7317522/132247293-35d0b4dc-ca6c-4791-8b7b-0c990edb7bbc.png)

Source is from fasthttp github.

An offtopic petition, can you add our latency/ping to the server with "Waiting started successfully"

**Comment by angrypie** [comment]
> perhaps golang is not optimized for such a number of cores, unfortunately I don't know how to fix it :( sorry

Hi @1makarov , this one hardworking loop very likely cause the problem. A little of "sleep" after each iteration would not hurt.

https://github.com/1makarov/binance-nft-buy/blob/2e7faa5cbca12b1e90217bd07d5c03ea82882607/internal/app/app.go#L50
