### ISSUE TITLE
как узнать номер nft дропа?

### ISSUE THREAD

**Issue by packrunner123** [1makarov/binance-nft-buy#15]
в шапке

**Comment by SamSeriousSam** [comment]
> в шапке
можно по подробнее ? в какой именно шапке ? на банане, на главной вроде ничего не писалось никогда, или может не обращал внимания.

**Comment by 1makarov** [comment]
![image](https://user-images.githubusercontent.com/38854356/133082663-a9ae7107-2761-457c-aea6-eb20bd76f855.png)

**Comment by packrunner123** [comment]
после авторизации не отображаются дропы, поэтому и спрашиваю

**Comment by 1makarov** [comment]
> после авторизации не отображаются дропы, поэтому и спрашиваю

Почему то завтрашнего дропа в целом нет в списках binance как mystery-box

**Comment by packrunner123** [comment]
понял, спасибо!
