### ISSUE TITLE
Ошибка при выполнении команды go run app.go

### ISSUE THREAD

**Issue by kENNYx7** [1makarov/binance-nft-buy#16]
Выполняю команду: go run app.go

Результат: 2021/09/13 15:21:28 error when reading response headers: EOF. Buffer size=8, contents: "\x00[\xd3wm^\xa1O"
exit status 1

Как решить эту проблему?

**Comment by 1makarov** [comment]
Привет, попробуй пересоздать файл .env. Возможно это ошибка кодировки headers'ов

**Comment by Flored777** [comment]
Что делать если у меня пишет go не является внутренней или внешней командой, исполняемой программой или пакетным файлом. Может я не туда засунул папку? Может в диск c надо? Или я неправильно файл env создал? Можешь ещё объяснить как этот файл правильно создать

**Comment by 1makarov** [comment]
> Что делать если у меня пишет go не является внутренней или внешней командой, исполняемой программой или пакетным файлом. Может я не туда засунул папку? Может в диск c надо? Или я неправильно файл env создал? Можешь ещё объяснить как этот файл правильно создать

Скорее всего неправильно установил golang, введи в консоль `go version` что тебе выдает?

**Comment by ROMAN1991777** [comment]
если показывает не последнюю версию стоит обновлять?

**Comment by ROMAN1991777** [comment]
![77777](https://user-images.githubusercontent.com/55110518/133147414-1e97174d-c358-40b3-8753-3a6907790fc7.png)
Проблема не решается 2 дня реально туплю уже
Решите кто нибудь мои муки)))))

**Comment by Bewwware** [comment]
У меня другая проблемма – как запустить команду go run app.go, если у меня MacOS?

**Comment by Znakomij** [comment]
> ![77777](https://user-images.githubusercontent.com/55110518/133147414-1e97174d-c358-40b3-8753-3a6907790fc7.png)
> Проблема не решается 2 дня реально туплю уже
> Решите кто нибудь мои муки)))))

Дай скрин свойств файла .env

**Comment by ROMAN1991777** [comment]
![33](https://user-images.githubusercontent.com/55110518/133165665-9c4d5991-cd00-4162-834e-0181a8e703bc.png)
с предыдущей ошибкой порешал прога запустилась один раз после повторного запуска новая ошибка

**Comment by ROMAN1991777** [comment]
> ![33](https://user-images.githubusercontent.com/55110518/133165665-9c4d5991-cd00-4162-834e-0181a8e703bc.png)
> с предыдущей ошибкой порешал прога запустилась один раз после повторного запуска новая ошибка
кто нибудь сталкивался с этим?

**Comment by Flored777** [comment]
> > Что делать если у меня пишет go не является внутренней или внешней командой, исполняемой программой или пакетным файлом. Может я не туда засунул папку? Может в диск c надо? Или я неправильно файл env создал? Можешь ещё объяснить как этот файл правильно создать
> 
> Скорее всего неправильно установил golang, введи в консоль `go version` что тебе выдает?

Мне пишет "go" не является внутренней или внешней командой, исполняемой программой или пакетным файлом

**Comment by kvazer13** [comment]
При запуске получаю ошибку:
Can't separate key from value

В чем может быть дело?

**Comment by kvazer13** [comment]
> При запуске получаю ошибку:
> Can't separate key from value
> 
> В чем может быть дело?

Разобрался. Не в той кодировке был сохранен файл .env

**Comment by Flored777** [comment]
> > При запуске получаю ошибку:
> > Can't separate key from value
> > В чем может быть дело?
> 
> Разобрался. Не в той кодировке был сохранен файл .env

А можешь подсказать как ты создавал файл env? Может я не так делаю

**Comment by kvazer13** [comment]
> > > При запуске получаю ошибку:
> > > Can't separate key from value
> > > В чем может быть дело?
> > 
> > 
> > Разобрался. Не в той кодировке был сохранен файл .env
> 
> А можешь подсказать как ты создавал файл env? Может я не так делаю

Создал текстовый документ, а потом "сохранить как", там выбираешь тип файла "все файлы" и сохраняешь его уже как .env

**Comment by ROMAN1991777** [comment]
![1111111111](https://user-images.githubusercontent.com/55110518/133246905-921e88b0-25bf-468c-b2c9-56460619a688.png)
Почему бот ничего не купил?

**Comment by Aist420** [comment]
> Выполняю команду: go run app.go
> 
> Результат: 2021/09/13 15:21:28 error when reading response headers: EOF. Buffer size=8, contents: "\x00[\xd3wm^\xa1O" exit status 1
> 
> Как решить эту проблему?

Пожалуйста, скажи, ты решил проблему??? у меня тоже самое
