### ISSUE TITLE
Ошибка error when reading response headers: EOF. Buffer size=8, contents:

### ISSUE THREAD

**Issue by Sitnikov6** [1makarov/binance-nft-buy#17]
![image](https://user-images.githubusercontent.com/90619437/133084454-09f7055a-cace-4160-835d-b071b508b70f.png)
Помогите с решением данной ошибки, буду очень благодарен.

**Comment by 1makarov** [comment]
Привет, попробуй пересоздать файл .env. Возможно это ошибка кодировки headers'ов

**Comment by Sitnikov6** [comment]
> Привет, попробуй пересоздать файл .env. Возможно это ошибка кодировки headers'ов

Удалить его и заново создать блокнотом потом изменить расширение txt на .env, верно?

**Comment by 1makarov** [comment]
> > Привет, попробуй пересоздать файл .env. Возможно это ошибка кодировки headers'ов
> 
> Удалить его и заново создать блокнотом потом изменить расширение txt на .env, верно?

да, и данные скопировать по новой с бинанса

**Comment by Sitnikov6** [comment]
> > > Привет, попробуй пересоздать файл .env. Возможно это ошибка кодировки headers'ов
> > 
> > 
> > Удалить его и заново создать блокнотом потом изменить расширение txt на .env, верно?
> 
> да, и данные скопировать по новой с бинанса

Проблема была в Proxy, убрал его сразу заработало, не знаю в чем проблема но с прокси не работает
