### ISSUE TITLE
Нету бокса в списке mystery box

### ISSUE THREAD

**Issue by Deathronik** [1makarov/binance-nft-buy#18]
Самого сейла в списке mystery box нету, ну при этом на страницу самого сейла можно попасть через главную страницу [binance nft](https://www.binance.com/ru/nft/home). Ссылка на сам сейл: https://www.binance.com/ru/nft/blindBox/detail?productId=133770228424308736. Как я понимаю, если бинанс не пофиксит трабл с отображением в mystery box то бот не будет работать. Нельзя ли по быстрому выпустить обнову в отдельной ветке которая будет на прямую брать данные о текущем сейле ?

**Comment by greetingsTraveler-mp3** [comment]
![изображение](https://user-images.githubusercontent.com/90629454/133099548-184ef9a9-61e8-4928-b19c-a33bba423e24.png)
