### ISSUE TITLE
Ошибка strconv.Atoi: parsing ***** : invalid syntax

### ISSUE THREAD

**Issue by dev1lon** [1makarov/binance-nft-buy#19]
![CqCZbZIzrHY](https://user-images.githubusercontent.com/90638030/133119769-2c1b0d08-091f-497f-af0d-473540715ff4.jpg)

За красной чертой  мой пароль.Все данные вводил правильно

**Comment by 1makarov** [comment]
proxy ввел в верном формате?

**Comment by dev1lon** [comment]
> proxy ввел в верном формате?

Вроде да , сначала ip свой, порт тоже , но насчёт него немного не понял , где его искать

**Comment by 1makarov** [comment]
В логине не присутствует @?

**Comment by retromen122** [comment]
> В логине не присутствует @?

 the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
 
 Не подскажешь в чем причина?

**Comment by retromen122** [comment]
> > В логине не присутствует @?
> 
> the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection
> 
> Не подскажешь в чем причина?

dialing to the given TCP address timed out
exit status 1 и вот эта появляется

**Comment by ADM4IK** [comment]
> proxy ввел в верном формате?

что писать если не использую прокси?

**Comment by ADM4IK** [comment]
дайте пожалуйста пример что писать в прокси(

**Comment by ADM4IK** [comment]
и если логин это емаил то как быть?)

**Comment by ADM4IK** [comment]
> > proxy ввел в верном формате?
> 
> Вроде да , сначала ip свой, порт тоже , но насчёт него немного не понял , где его искать
> Логин и пароль верно ввёл

ты не разобрался?

**Comment by 1makarov** [comment]
> > proxy ввел в верном формате?
> 
> что писать если не использую прокси?

ничего

**Comment by ADM4IK** [comment]
> > > proxy ввел в верном формате?
> > 
> > 
> > что писать если не использую прокси?
> 
> ничего

только логин и пароль от бинанса? и что писать в логине если захожу через емаил или номер?

**Comment by hnsik** [comment]
> > > > proxy ввел в верном формате?
> > > 
> > > 
> > > что писать если не использую прокси?
> > 
> > 
> > ничего
> 
> только логин и пароль от бинанса? и что писать в логине если захожу через емаил или номер?

Если ты не используешь прокси то пишешь так PROXY=
Если используешь PROXY=proxylogin:proxypassword@host:port

**Comment by ADM4IK** [comment]
> > > > > proxy ввел в верном формате?
> > > > 
> > > > 
> > > > что писать если не использую прокси?
> > > 
> > > 
> > > ничего
> > 
> > 
> > только логин и пароль от бинанса? и что писать в логине если захожу через емаил или номер?
> 
> Если ты не используешь прокси то пишешь так PROXY=
> Если используешь PROXY=proxylogin:proxypassword@host:port

спасибо друг) все получилось

**Comment by Kekovich2018** [comment]
а как создать файл .env ?

**Comment by dev1lon** [comment]
> > > > > proxy ввел в верном формате?
> > > > 
> > > > 
> > > > что писать если не использую прокси?
> > > 
> > > 
> > > ничего
> > 
> > 
> > только логин и пароль от бинанса? и что писать в логине если захожу через емаил или номер?
> 
> Если ты не используешь прокси то пишешь так PROXY=
> Если используешь PROXY=proxylogin:proxypassword@host:port

Спасибо друг , всё получилось

**Comment by Gercrf** [comment]
> ![CqCZbZIzrHY](https://user-images.githubusercontent.com/90638030/133119769-2c1b0d08-091f-497f-af0d-473540715ff4.jpg)
> 
> За красной чертой мой пароль.Все данные вводил правильно

такая же проблема
как решить?
