### ISSUE TITLE
Delay,обновление гайда

### ISSUE THREAD

**Issue by ZlouNyan** [1makarov/binance-nft-buy#2]
Прости меня что пложу лишние иссы,но не мог бы подсказать какие задержки принимает бот,а также не нужна ли тебе помощь в обновлении инструкции для программы?)

**Comment by Holodun406** [comment]
Привет, а минус 1 секунда принимает? В прошлом сейле ничего не взял, отключили раздачу и возобновили где то через минуту.

**Comment by 1makarov** [comment]
Привет, по сути, должно работать. Но как на деле, не проверял.

**Comment by senyka001k** [comment]
Sale number это Id сейла ?

**Comment by 1makarov** [comment]
Привет, sale number это айди сейла из списка
