### ISSUE TITLE
Стратегия запросов

### ISSUE THREAD

**Issue by newbie-soft** [1makarov/binance-nft-buy#22]
Макар, хотел бы у тебя поинтересоваться, ты не экспериментировал с частотой запросов? Если delay между запросами меньше 1 секунды - временно ли блокирует бинанс их отправление? Или можно, грубо говоря, за одну секунду 50 запросов послать?

**Comment by 1makarov** [comment]
При 5 одновременных запросах происходит блокировка.

**Comment by newbie-soft** [comment]
> При 5 одновременных запросах происходит блокировка.

А период между запросами имеет значение?
