### ISSUE TITLE
Как делаешь запросы на покупку боксов?

### ISSUE THREAD

**Issue by matvey-dev** [1makarov/binance-nft-buy#23]
Пытался разобраться с тем, как ты запросы посылаешь, но с GO не знаком)
У binance есть какие-то прямые endpoint`s?
Или ты как то парсишь html и нажимаешь кнопку на сайте?)))

ps: Можно в лс.
связь tg - @matvey_dev
vk.com/wannafckingdie

**Comment by newbie-soft** [comment]
Лол, просто посылаешь запросы и всё

**Comment by matvey-dev** [comment]
> Лол, просто посылаешь запросы и всё
есть документация?

**Comment by DmitrySidorow** [comment]
А причем тут go и как посылаются запросы?

**Comment by matvey-dev** [comment]
Ну этот скрипт на GO написан.
Я имею ввиду есть документация по запросам к бинансу?
Я просто искал такие запросы и не нашел

**Comment by DmitrySidorow** [comment]
> Ну этот скрипт на GO написан.
> Я имею ввиду есть документация по запросам к бинансу?
> Я просто искал такие запросы и не нашел

слишком тупо, если бы они написали документацию на покупку NFT) только самому копать.

**Comment by matvey-dev** [comment]
> > Ну этот скрипт на GO написан.
> > Я имею ввиду есть документация по запросам к бинансу?
> > Я просто искал такие запросы и не нашел
> 
> слишком тупо, если бы они написали документацию на покупку NFT) только самому копать.
> ну а по поводу go, то без знания легко все читается вроде, какие запросы и как делаются. я на питон изи перенес


Смог купить боксы?

**Comment by AN1123** [comment]
![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
даже с задержкой в ​​1 мс я не мог купить.

**Comment by DmitrySidorow** [comment]
> ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> даже с задержкой в ​​1 мс я не мог купить.

естественно не смог, потому что он начал работать раньше на несколько секунд.

**Comment by AndrewPoarch** [comment]
> ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> даже с задержкой в ​​1 мс я не мог купить.

как посмотреть задержку

**Comment by nikital111** [comment]
Пытаюсь перенести скрипт на js, при покупке бокса выдает ошибку 500, может кто-то сталкивался?

**Comment by AN1123** [comment]
> > ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> > ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> > even with a 1ms delay I could not buy.
> 
> how to view the delay

![image](https://user-images.githubusercontent.com/90413531/133273839-70780712-8a1e-4bf2-907c-f02d4b68b170.png)

**Comment by fokysnik21** [comment]
> > > ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> > > ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> > > even with a 1ms delay I could not buy.
> > 
> > 
> > how to view the delay
> 
> ![image](https://user-images.githubusercontent.com/90413531/133273839-70780712-8a1e-4bf2-907c-f02d4b68b170.png)

Hello, please tell me what is your server, what is such a small delay?

**Comment by LimberGG** [comment]
> ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> даже с задержкой в ​​1 мс я не мог купить.

Может кто-то подсказать? На этих скринах много запросов за 1 секунду, у меня получается 1 запрос в 1 секунду, так в терминале отображается. Правильно ли я понял, что частота запросов повышается заменой параметра (internal/app/app.go): time.Sleep(1 * time.Second) на условный  time.Sleep(1 * time.Millisecond)? или тут зависит больше от пинга? он у меня примерно 50ms до www.binance.com.
Заранее спасибо !=)
