### ISSUE TITLE
Что будет если не использовать прокси?

### ISSUE THREAD

**Issue by RoadZarabotok** [1makarov/binance-nft-buy#24]
Привет, стало интересно, произойдёт ли что то если не использовать прокси, то бишь могут ли забанить или что то в этом духе?

**Comment by AndrewPoarch** [comment]
> Привет, стало интересно, произойдёт ли что то если не использовать прокси, то бишь могут ли забанить или что то в этом духе?

Ну если ты только одну программу используешь то не надо
