### ISSUE TITLE
Ошибка The system cannot find the file specified.

### ISSUE THREAD

**Issue by Kekovich2018** [1makarov/binance-nft-buy#27]
![image](https://user-images.githubusercontent.com/39415854/133222250-69f46a96-9d53-45f9-ae02-d1502f441724.png)

**Comment by ADM4IK** [comment]
перейди C:\Users\"имя твоего профиля"\ там будет файлик GO удали его и заново запускай

**Comment by Kekovich2018** [comment]
я его удалил, но это не помогло

**Comment by Kekovich2018** [comment]
я его удалил, но это не помогло
