### ISSUE TITLE
кто купил с помощью этого бота? в LFW Mystery Box

### ISSUE THREAD

**Issue by golushko** [1makarov/binance-nft-buy#28]
кто купил с помощью этого бота? в LFW Mystery Box

**Comment by Targan** [comment]
сервер перегружен

**Comment by SamSeriousSam** [comment]
такая же история

**Comment by Ivantesss** [comment]
У меня вообще ничего не пошло
![Uploading 981AA5B7-F9F2-4416-A2FD-537C9BF853D8.png…]()

**Comment by AndreasFxPro** [comment]
так же, сервер перегружен

**Comment by rada112** [comment]
слишком рано начинает запросы слать, потом в бан уходит просто

**Comment by Holodun406** [comment]
![image](https://user-images.githubusercontent.com/81082714/133248886-e90aceba-ced5-4f93-bea7-0d8907815050.png)

**Comment by hnsik** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/59423354/133249161-33bb7882-cb8a-4cd3-95be-5dc9a4b4306b.png)

**Comment by AndreasFxPro** [comment]
![зображення](https://user-images.githubusercontent.com/47606652/133249460-0e656786-4cb8-4723-92fb-c0638aee0445.png)

**Comment by OlegKorsa777** [comment]
То же самое(

**Comment by Aveavega** [comment]
Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
Ща пилим свой софт.

**Comment by keshinogattsu** [comment]
> Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> Ща пилим свой софт.
Возможно будет его купить?

**Comment by developerdaun** [comment]
> > Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> > Ща пилим свой софт.
> > Возможно будет его купить?

Та надо сначала разобраться, сделать, оттестить...

**Comment by 1makarov** [comment]
> Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> Ща пилим свой софт.

Ждём!

**Comment by DaveBer** [comment]
> > Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> > Ща пилим свой софт.
> 
> Ждём!

Из-за чего у всех такая проблема была сегодня? Что-то надо доделать в боте?

**Comment by AndreasFxPro** [comment]
> 
> 
> Бот х.. Целая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> Ща пилим свой софт.

Слушай, а я могу чем-то помочь?
У тебя есть телеграмм? Напиши мне плиз, @Andreas407

**Comment by NeiTRoN96** [comment]
> Бот х.. Целая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> Ща пилим свой софт.

Вам человек бесплатно выложил свою работу, а вы еще обсираете. Не в проге проблема. В сейле было 9600 шт, каждый мог купить по 20. Итого 480 человек со всего бинанса все забрать могли. Продажи стартуют для всех в одну секунду и она известна всем. Вот и представьте, что происходит в эту секунду..

**Comment by AndreasFxPro** [comment]
> 
> 
> > Бот х.. Целая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> > Ща пилим свой софт.
> 
> Вам человек бесплатно выложил свою работу, а вы еще обсираете. Не в проге проблема. В сейле было 9600 шт, каждый мог купить по 20. Итого 480 человек со всего бинанса все забрать могли. Продажи стартуют для всех в одну секунду и она известна всем. Вот и представьте, что происходит в эту секунду..

что происходит со стороны сервера))

**Comment by NeiTRoN96** [comment]
> > > Бот х.. Целая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> > > Ща пилим свой софт.
> > 
> > 
> > Вам человек бесплатно выложил свою работу, а вы еще обсираете. Не в проге проблема. В сейле было 9600 шт, каждый мог купить по 20. Итого 480 человек со всего бинанса все забрать могли. Продажи стартуют для всех в одну секунду и она известна всем. Вот и представьте, что происходит в эту секунду..
> 
> что происходит со стороны сервера))

Именно.. Это тупо везение, кто заберет.

**Comment by NeiTRoN96** [comment]
@1makarov А подскажи, ты не пробовал работать с запросом на https://www.binance.com/bapi/nft/v1/public/nft/market-mystery/mystery-list . Никак не получается, что уже только не пробовал все пишет "illegal parameter". Спасибо в любом случае

**Comment by DaveBer** [comment]
> > > > Бот х.. Целаая банда нас собралась. Никто ничего не купил с его помощью... А сейл был неплохой(((
> > > > Ща пилим свой софт.
> > > 
> > > 
> > > Ждём!
> > 
> > 
> > Из-за чего у всех такая проблема была сегодня? Что-то надо доделать в боте?
> 
> Из-за того что сервер перегружен, написано ведь

Я думал это из-за частоты запросов, поэтому спросил
В любом случае, спасибо за бота!

**Comment by 1makarov** [comment]
> @1makarov А подскажи, ты не пробовал работать с запросом на https://www.binance.com/bapi/nft/v1/public/nft/market-mystery/mystery-list . Никак не получается, что уже только не пробовал все пишет "illegal parameter". Спасибо в любом случае

Можно скриншот?

**Comment by NeiTRoN96** [comment]
> > @1makarov А подскажи, ты не пробовал работать с запросом на https://www.binance.com/bapi/nft/v1/public/nft/market-mystery/mystery-list . Никак не получается, что уже только не пробовал все пишет "illegal parameter". Спасибо в любом случае
> 
> Можно скриншот?

![Мистери рынок](https://user-images.githubusercontent.com/65417053/133375194-30cfac8a-86e5-4bf2-9c99-03311a78ced7.png)

На странице https://www.binance.com/ru/nft/blindBox/market при установке фильтров срабатывает этот запрос. Пробовал и без параметров и с параметрами - всегда ответ "illegal parameter"

**Comment by DmitrySidorow** [comment]
> > > @1makarov А подскажи, ты не пробовал работать с запросом на https://www.binance.com/bapi/nft/v1/public/nft/market-mystery/mystery-list . Никак не получается, что уже только не пробовал все пишет "illegal parameter". Спасибо в любом случае
> > 
> > 
> > Можно скриншот?
> 
> ![Мистери рынок](https://user-images.githubusercontent.com/65417053/133375194-30cfac8a-86e5-4bf2-9c99-03311a78ced7.png)
> 
> На странице https://www.binance.com/ru/nft/blindBox/market при установке фильтров срабатывает этот запрос. Пробовал и без параметров и с параметрами - всегда ответ "illegal parameter"

Неправильно запрос отправляешь

**Comment by NeiTRoN96** [comment]
> > > > @1makarov А подскажи, ты не пробовал работать с запросом на https://www.binance.com/bapi/nft/v1/public/nft/market-mystery/mystery-list . Никак не получается, что уже только не пробовал все пишет "illegal parameter". Спасибо в любом случае
> > > 
> > > 
> > > Можно скриншот?
> > 
> > 
> > ![Мистери рынок](https://user-images.githubusercontent.com/65417053/133375194-30cfac8a-86e5-4bf2-9c99-03311a78ced7.png)
> > На странице https://www.binance.com/ru/nft/blindBox/market при установке фильтров срабатывает этот запрос. Пробовал и без параметров и с параметрами - всегда ответ "illegal parameter"
> 
> Неправильно запрос отправляешь

😄 Это я знаю..

**Comment by Nelegal1378** [comment]
Всем привет, есть бот-запросник с обходом капчи. По вопросам пишите в телегу - @godzila_bott. Всё покажу, расскажу с удовольствием
