### ISSUE TITLE
С этим возможно бороться?

### ISSUE THREAD

**Issue by Alaaois** [1makarov/binance-nft-buy#29]
Как я понял такое побороть своими силами нельзя? Может ли это связано с недосточно быстрыми прокси?
![image](https://user-images.githubusercontent.com/90388466/133247409-0b6c6b05-c0cc-4806-b3ca-c0f91ccf49c8.png)

**Comment by Targan** [comment]
Тоже самое

**Comment by AN1123** [comment]
Тоже самое

**Comment by Ev1LOFF** [comment]
Такая же тема. Может сделать запросы чаще чем 1 раз в секунду?

**Comment by DmitrySidorow** [comment]
Вы думаете, что просто так сможете взять кейсы по 20$, которые по 150$ отлетают?
Таких как вы десятки тысяч.

**Comment by nevernigh** [comment]
> Вы думаете, что просто так сможете взять кейсы по 20$, которые по 150$ отлетают?
> Таких как вы десятки тысяч.

согласен

**Comment by nikital111** [comment]
мне даже с компа так писало, это бинанс
