### ISSUE TITLE
Go: многопоточность и параллельность

### ISSUE THREAD

**Issue by vyshnovskyi** [1makarov/binance-nft-buy#31]
Привет, на сколько я понял за 1 секунду можно отправить не более 5 запросов иначе блок. Может тогда сделать многопоточность и слать каждую секунду 4 запроса не ожидаясь ответа от сервера ?

**Comment by 1makarov** [comment]
Привет, это примерные цифры, не делал точных тестов на блокировку. Ибо она происходит исключительно в течение сейлов.
