### ISSUE TITLE
Вопрос по работе запросов

### ISSUE THREAD

**Issue by LimberGG** [1makarov/binance-nft-buy#33]
> ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> даже с задержкой в ​​1 мс я не мог купить.

Может кто-то подсказать? На этих скринах много запросов за 1 секунду, у меня получается 1 запрос в 1 секунду, так в терминале отображается. Правильно ли я понял, что частота запросов повышается заменой параметра (internal/app/app.go): time.Sleep(1 * time.Second) на условный  time.Sleep(1 * time.Millisecond)? или тут зависит больше от пинга? он у меня примерно 50ms до www.binance.com.
И вот еще вопрос, уменьшается ли ping во время работы приложения, по средствам использования fasthttp (имею ввиду одинаковый ли будет пинг при пинговке просто бинанса и при работе приложения с этим модулем) 
Заранее спасибо !=)

_Originally posted by @LimberGG in https://github.com/1makarov/binance-nft-buy/issues/23#issuecomment-919890920_

**Comment by dhaern** [comment]
Can you stop give more info to noobs? when more "issues" and screenshots you post, you will have more competition and less money for you... ffs use your brain guys, this shit is getting out of hands. Delete this post and stop this.

**Comment by Holodun406** [comment]
> > ![image](https://user-images.githubusercontent.com/90413531/133247347-5e77bcea-b313-42ba-a794-5b359aaf33a8.png)
> > ![image](https://user-images.githubusercontent.com/90413531/133247369-ddd2a5d0-9019-4b58-9d00-9eaa14c21f1b.png)
> > даже с задержкой в ​​1 мс я не мог купить.
> 
> Может кто-то подсказать? На этих скринах много запросов за 1 секунду, у меня получается 1 запрос в 1 секунду, так в терминале отображается. Правильно ли я понял, что частота запросов повышается заменой параметра (internal/app/app.go): time.Sleep(1 * time.Second) на условный time.Sleep(1 * time.Millisecond)? или тут зависит больше от пинга? он у меня примерно 50ms до [www.binance.com](http://www.binance.com).
> И вот еще вопрос, уменьшается ли ping во время работы приложения, по средствам использования fasthttp (имею ввиду одинаковый ли будет пинг при пинговке просто бинанса и при работе приложения с этим модулем)
> Заранее спасибо !=)
> 
> _Originally posted by @LimberGG in [#23 (comment)](https://github.com/1makarov/binance-nft-buy/issues/23#issuecomment-919890920)_

Thank you friend!

**Comment by izzgoy** [comment]
За что отвечает эта команда? app.go 
time.Sleep(6 * time.Second) 
box.Status = true

**Comment by izzgoy** [comment]
И как сделать чтобы бот делал например только 20 запросов
