### ISSUE TITLE
Как обойти анти-бот защиту при запросе product-onsale

### ISSUE THREAD

**Issue by newbie-soft** [1makarov/binance-nft-buy#34]
Делают такую фичу на TeamperMonkey. Все работает на запросах.
Но есть некоторые проблемы:
1. Так понимаю 'csrftoken' никак не получить из под TeamperMonkey? ОК, будем вводить в ручном режиме.
2. Появилась проблема при размещении товара на продажу (запрос product-onsale). Там, судя по всему, стоит антибот защита, в заголовке запроса подтягиваются доп. данные по аккаунту и компьютеру. В какую сторону копать?

![image](https://user-images.githubusercontent.com/84334192/133465895-4a7d168b-2cf2-4307-9006-2f3adaa8a0ee.png)

**Comment by 1makarov** [comment]
Там стоит recaptcha v3, её обходить исключительно через rucaptcha/antigate и тд

**Comment by newbie-soft** [comment]
> Стоит recaptcha v3, её обходить исключительно через rucaptcha/antigate и тд

А вот сейчас по запросам потестил, вроде бы именно на выставление на маркет - требуется рекапчка 2.

**Comment by grandmaster451** [comment]
> Делают такую фичу на TeamperMonkey. Все работает на запросах.
> Но есть некоторые проблемы:
> 
> 1. Так понимаю 'csrftoken' никак не получить из под TeamperMonkey? ОК, будем вводить в ручном режиме.
> 2. Появилась проблема при размещении товара на продажу (запрос product-onsale). Там, судя по всему, стоит антибот защита, в заголовке запроса подтягиваются доп. данные по аккаунту и компьютеру. В какую сторону копать?
> 
> ![image](https://user-images.githubusercontent.com/84334192/133465895-4a7d168b-2cf2-4307-9006-2f3adaa8a0ee.png)

подскажите, что за плагин такой, который показывает цены?

**Comment by newbie-soft** [comment]
> > Делают такую фичу на TeamperMonkey. Все работает на запросах.
> > Но есть некоторые проблемы:
> > 
> > 1. Так понимаю 'csrftoken' никак не получить из под TeamperMonkey? ОК, будем вводить в ручном режиме.
> > 2. Появилась проблема при размещении товара на продажу (запрос product-onsale). Там, судя по всему, стоит антибот защита, в заголовке запроса подтягиваются доп. данные по аккаунту и компьютеру. В какую сторону копать?
> > 
> > ![image](https://user-images.githubusercontent.com/84334192/133465895-4a7d168b-2cf2-4307-9006-2f3adaa8a0ee.png)
> 
> подскажите, что за плагин такой, который показывает цены?

Это userscript на TeamperMonkey (расширение для поддержки userscript в Google Chrome).
Скрипт я пишу сам.

**Comment by grandmaster451** [comment]
> > > Делают такую фичу на TeamperMonkey. Все работает на запросах.
> > > Но есть некоторые проблемы:
> > > 
> > > 1. Так понимаю 'csrftoken' никак не получить из под TeamperMonkey? ОК, будем вводить в ручном режиме.
> > > 2. Появилась проблема при размещении товара на продажу (запрос product-onsale). Там, судя по всему, стоит антибот защита, в заголовке запроса подтягиваются доп. данные по аккаунту и компьютеру. В какую сторону копать?
> > > 
> > > ![image](https://user-images.githubusercontent.com/84334192/133465895-4a7d168b-2cf2-4307-9006-2f3adaa8a0ee.png)
> > 
> > 
> > подскажите, что за плагин такой, который показывает цены?
> 
> Это userscript на TeamperMonkey (расширение для поддержки userscript в Google Chrome).
> Скрипт я пишу сам.

если бы вам не составило труда опубликовать, я был бы вам очень благодарен, видите ли, я сам пока что не способен создать подобное)
