### ISSUE TITLE
Можно ли покупать руками и при этом чтобы работал бот?

### ISSUE THREAD

**Issue by Flored777** [1makarov/binance-nft-buy#35]
Можно ли покупать руками и при этом чтобы работал бот?

**Comment by 1makarov** [comment]
конечно

**Comment by Flored777** [comment]
> конечно

Ему это вообще не помешает?

**Comment by 1makarov** [comment]
> > конечно
> 
> Ему это вообще не помешает?

Если перезаходить не будешь - нет должно, потести. Не пробовал

**Comment by Flored777** [comment]
> > > конечно
> > 
> > 
> > Ему это вообще не помешает?
> 
> Если перезаходить не будешь - нет должно, потести. Не пробовал

Во время дропа страшновато тестить
