### ISSUE TITLE
Вылетает ошибка

### ISSUE THREAD

**Issue by Gercrf** [1makarov/binance-nft-buy#36]
![image](https://user-images.githubusercontent.com/78883609/133474484-7d0c9aaa-361b-4f57-9bbf-b392fb331fcf.png)

**Comment by Gercrf** [comment]
Такая ошибка в любом случае( 
И бот на реквестах работает?

**Comment by 1makarov** [comment]
тут нет твоего ответа https://github.com/1makarov/binance-nft-buy/issues/19 ?

**Comment by Gercrf** [comment]
> тут нет твоего ответа #19 ?

Неа, я так и не смог исправить

**Comment by Gercrf** [comment]
Там нету ответа на эту ошибку, в том и проблема наверное

**Comment by 1makarov** [comment]
> > тут нет твоего ответа #19 ?
> 
> Неа, я так и не смог исправить

Тогда вряд ли смогу помочь, явно что-то не так вводишь, ибо не может спарситься

**Comment by Gercrf** [comment]
Ввожу просто обычным англом пароль 
И именно ему не нравится пароль
PROXY=pochta@gmail.com:qwerty12345@host:port (optional)
Так должно выглядеть?

**Comment by 1makarov** [comment]
> Ввожу просто обычным англом пароль
> И именно ему не нравится пароль
> PROXY=[pochta@gmail.com](mailto:pochta@gmail.com):qwerty12345@host:port (optional)
> Так должно выглядеть?

Без (optional), так же не должно быть @ в логине

**Comment by Gercrf** [comment]
Хмм
А с почтой как?

**Comment by 1makarov** [comment]
> Хмм
> А с почтой как?

Какой почтой?

**Comment by Gercrf** [comment]
Если логин, почта?
Без @?

**Comment by 1makarov** [comment]
> Если логин, почта?
> Без @?

Если логин от прокси это почта, тогда стоит поменять логин, он должен быть обязательно без @

**Comment by Gercrf** [comment]
Бля друг хахаха
Логин и Пароль от проксей ахахаха

**Comment by Gercrf** [comment]
Ты про это хахах, а я от бинанса ввожу

**Comment by Flored777** [comment]
> Ты про это хахах, а я от бинанса ввожу
Я тоже так думал когда увидел что надо вписать, но потом догадался
