### ISSUE TITLE
Смогу ли я запустить бота рано утром и уйти по делам?

### ISSUE THREAD

**Issue by izzgoy** [1makarov/binance-nft-buy#37]
Смогу ли я запустить бота рано утром и уйти по делам? Или мне нужно запустить бота за полчаса до сейла?

**Comment by 1makarov** [comment]
Можешь запустить в любое время

**Comment by izzgoy** [comment]
> Можешь запустить в любое время

типа я могу утром запустить и не торкаться компютера и он все равно купит?

**Comment by Vergervan** [comment]
> > Можешь запустить в любое время
> 
> типа я могу утром запустить и не торкаться компютера и он все равно купит?

Да, бот будет ожидать до времени старта продаж, и в это время ничё не делать

**Comment by DmitrySidorow** [comment]
> > Можешь запустить в любое время
> 
> типа я могу утром запустить и не торкаться компютера и он все равно купит?
конечно, бро. он даже продаст сам паки в x5

**Comment by SamSeriousSam** [comment]
приветствую, если прокси введены не правильном формате, то бот не запуститься ? ввел прокси в формате как по мануалу, выбрал дроп, ввел количество, бот встал в ожидание, значит прокси работают как положено и введено без ошибок ?

**Comment by SamSeriousSam** [comment]
подскажите еще пожалуйста , как настроить бот, чтобы делал больше запросов в секунду ? не понимаю как
