### ISSUE TITLE
параметры пост запроса

### ISSUE THREAD

**Issue by random1guy** [1makarov/binance-nft-buy#38]
йоу, пытаюсь своего бота написать, но чет застрял. В пост запросе попробовал много комбинаций параметров, но серв кидает ошибку "need to log in to access", вроде все куки и csrf токены указал. Не знаешь в чем может быть трабла?

**Comment by 1makarov** [comment]
возможно content-type забыл

**Comment by random1guy** [comment]
да нет, он есть. Я правильно понимаю, что мы сначала кидаем на base-detail запрос?

**Comment by random1guy** [comment]
@1makarov сидел искал по логам network'а url https://www.binance.com/bapi/nft/v1/private/nft/mystery-box/purchase, чтобы узнать соответствующие параметры, но пока нигде не увидел. Есть предположение, что он появляется во время самого сейла... не подскажешь куда копать?

**Comment by 1makarov** [comment]
> @1makarov сидел искал по логам network'а url https://www.binance.com/bapi/nft/v1/private/nft/mystery-box/purchase, чтобы узнать соответствующие параметры, но пока нигде не увидел. Есть предположение, что он появляется во время самого сейла... не подскажешь куда копать?

ну это url запроса на покупку, понятно что он появляется в момент нажатия на кнопку покупки

**Comment by Alex79875868** [comment]
Здравствуйте, у меня возникла такая же проблема. Не могли бы вы подсказать параметры и заголовки пост запроса для покупки?

**Comment by Juonior** [comment]
Привет, ребят. Получилось решить?

**Comment by vovan770124** [comment]
такая же муйня с https://www.binance.com/bapi/margin/v1/private/new-otc/get-quote   .   кандоны, не могут а апи запихать всю эту коляску.  все поддержки орут че нет такого апи типа, почту разрабов не дают. бешенные ботмейкеры которые типа полторы тысячи торговых ботов написали и продают тоже не в курсе этого апи. через панель разраба тож вытащил этот адрес и параметры Post,  и тож орет че авторизация нужна сначала. так то логично она /private.  хрен с ней, щас кишки пойду выпускать у HTTPReq...

**Comment by vovan770124** [comment]
> йоу, пытаюсь своего бота написать, но чет застрял. В пост запросе попробовал много комбинаций параметров, но серв кидает ошибку "need to log in to access", вроде все куки и csrf токены указал. Не знаешь в чем может быть трабла?
это блятство, авторизацию, не закидывал с запросом  ?
url := 'https://api.binance.com/api/v3/account?';
      queryString :='timestamp=' + nonce;
      sign := THashSHA2.GetHMAC(queryString, FApiKey, SHA256);

      idHTTP10.HandleRedirects := True;
      idHTTP10.Request.CustomHeaders.Add('X-MBX-APIKEY:' + FApiKey);

      url := url + queryString + '&signature=' + sign;
      try
         idHTTP10.Get(url, responeJsonMemory);
      except

**Comment by vovan770124** [comment]
> йоу, пытаюсь своего бота написать, но чет застрял. В пост запросе попробовал много комбинаций параметров, но серв кидает ошибку "need to log in to access", вроде все куки и csrf токены указал. Не знаешь в чем может быть трабла?

типа этого блятства, авторизацию, не закидывал с запросом ?
url := 'https://api.binance.com/api/v3/account?';
queryString :='timestamp=' + nonce;
sign := THashSHA2.GetHMAC(queryString, FApiKey, SHA256);

  idHTTP10.HandleRedirects := True;
  idHTTP10.Request.CustomHeaders.Add('X-MBX-APIKEY:' + FApiKey);

  url := url + queryString + '&signature=' + sign;
  try
     idHTTP10.Get(url, responeJsonMemory);
  except

**Comment by vovan770124** [comment]
> йоу, пытаюсь своего бота написать, но чет застрял. В пост запросе попробовал много комбинаций параметров, но серв кидает ошибку "need to log in to access", вроде все куки и csrf токены указал. Не знаешь в чем может быть трабла?

типа этого блятства, авторизацию, не закидывал с запросом ?
....... GetSystemTime(&ST);
		DT = EncodeDate(ST.wYear, ST.wMonth, ST.wDay) + EncodeTime(ST.wHour, ST.wMinute, ST.wSecond, ST.wMilliseconds);
		uTime = MilliSecondsBetween(DT, UnixDateDelta);
		nonce = IntToStr(uTime); url = "https://api.binance.com/api/v3/account?";
		nonce=gt;
		queryString = "timestamp=" + nonce;
		sign = thash2.GetHMAC(RawByteString(queryString), ApiPrivateKey);             // <---------------
		IdHTTP1->Request->CustomHeaders->Add("X-MBX-APIKEY:" + ApiKey);      // <---------------
		IdHTTP1->Request->CustomHeaders->Add("Accept: application/json");
		IdHTTP1->Request->CustomHeaders->Add("User-Agent: tesla 1.1");
		url = url + queryString + "&signature=" + sign;
		try
		{
			responeJsonMemory->Position=0;	responeJsonMemory->Clear();
			IdHTTP1->Get(url, responeJsonMemory); .........

**Comment by arizorin** [comment]
> Привет, ребят. Получилось решить?

clienttype: web добавь
