### ISSUE TITLE
Is thery  Python version ?

### ISSUE THREAD

**Issue by lidd77** [1makarov/binance-nft-buy#40]
Hey,  
Could we develop a Python version ?

**Comment by matvey-dev** [comment]
> Hey,
> Could we develop a Python version ?

Hello, are you developer?
send message to me in telegram @matvey_dev

**Comment by lidd77** [comment]
> > Hey,
> > Could we develop a Python version ?
> 
> Hello, are you developer? send message to me in telegram @matvey_dev

Can not send you message without mutual contacts in TG
