### ISSUE TITLE
Не работает go run app.go

### ISSUE THREAD

**Issue by LuckyFecher** [1makarov/binance-nft-buy#41]
Что нужно сделать, подскажите пожалуйста?!
![image](https://user-images.githubusercontent.com/74074638/133584339-c3e52adc-cd08-4293-802e-57ed25abc56b.png)

**Comment by Nekspsy** [comment]
Точно такая же проблема, пока решение не нашел...
p.s ты не из крыма?

**Comment by LuckyFecher** [comment]
> Точно такая же проблема, пока решение не нашел...
> p.s ты не из крыма?

из крыма, да

**Comment by LuckyFecher** [comment]
Вопрос, а если под впн настроить бота, выставить номер и кол-во для покупки и когда бот ожидает появления лотов, вырубить впн, будет ли он работает?

**Comment by LuckyFecher** [comment]
судя по всему нет, т.к. бинанс вылетает из акка

**Comment by Nekspsy** [comment]
> > Точно такая же проблема, пока решение не нашел...
> > p.s ты не из крыма?
> 
> ДЛЯ ТЕХ КТО ИЗ КРЫМА, ЮЗАЕМ ВПН!!!
> ВСЕ РАБОТАЕТ!
> В прокси не вводите лог и пасс от бинанса!!! Всем удачных покупок!

подскажи, пожалуйста, какой впн используешь? кучу всего перепробовал, этот пакет как у автора ветки так и не удается скачать. Вручную через браузер (с впном) качается пакет, дальше пытался вручную положить его куда надо, но не помогло, пробовал куда только можно. А вот через консоль как пустить трафик через впн - без понятия.

**Comment by LuckyFecher** [comment]
> > > Точно такая же проблема, пока решение не нашел...
> > > p.s ты не из крыма?
> > 
> > 
> > ДЛЯ ТЕХ КТО ИЗ КРЫМА, ЮЗАЕМ ВПН!!!
> > ВСЕ РАБОТАЕТ!
> > В прокси не вводите лог и пасс от бинанса!!! Всем удачных покупок!
> 
> подскажи, пожалуйста, какой впн используешь? кучу всего перепробовал, этот пакет как у автора ветки так и не удается скачать. Вручную через браузер (с впном) качается пакет, дальше пытался вручную положить его куда надо, но не помогло, пробовал куда только можно. А вот через консоль как пустить трафик через впн - без понятия.

Так ну смотри, я все делал без впн, до включения го ран, а так windscribe юзаю, все без впна делай, а впн только залогиниться в бинанс + под впн включить ботам через cmd, все, и сиди под впн, иначе бинанс оффнит акк и бот не купит не че

**Comment by Nekspsy** [comment]
> Так ну смотри, я все делал без впн, до включения го ран, а так windscribe юзаю, все без впна делай, а впн только залогиниться в бинанс + под впн включить ботам через cmd, все, и сиди под впн, иначе бинанс оффнит акк и бот не купит не че

Сори, немного запутано написал)
Попробовал windscribe, результат такой же:

```
C:\binance-nft-buy-master>go run app.go
go: downloading github.com/klauspost/compress v1.13.1
C:\Users\Neks\go\pkg\mod\github.com\valyala\fasthttp@v1.28.0\compress.go:10:2: github.com/klauspost/compress@v1.13.1: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.1.zip: 403 Forbidden
```

Почему-то трафик в консоли не через впн идёт...

**Comment by LuckyFecher** [comment]
> > Так ну смотри, я все делал без впн, до включения го ран, а так windscribe юзаю, все без впна делай, а впн только залогиниться в бинанс + под впн включить ботам через cmd, все, и сиди под впн, иначе бинанс оффнит акк и бот не купит не че
> 
> Сори, немного запутано написал)
> Попробовал windscribe, результат такой же:
> 
> ```
> C:\binance-nft-buy-master>go run app.go
> go: downloading github.com/klauspost/compress v1.13.1
> C:\Users\Neks\go\pkg\mod\github.com\valyala\fasthttp@v1.28.0\compress.go:10:2: github.com/klauspost/compress@v1.13.1: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.13.1.zip: 403 Forbidden
> ```
> 
> Почему-то трафик в консоли не через впн идёт...

блин, а вот тут я уже хз, сам чайник, если бы ты не написал про крым, я бы тупил сидел. чекни меняется ли айпишник, попробуй ребутнуть роутер+комп, хз даже блин(

**Comment by Nekspsy** [comment]
> блин, а вот тут я уже хз, сам чайник, если бы ты не написал про крым, я бы тупил сидел. чекни меняется ли айпишник, попробуй ребутнуть роутер+комп, хз даже блин(

алилуя, разобрался) спасибо, бро, за ответы :)

**Comment by LuckyFecher** [comment]
> > блин, а вот тут я уже хз, сам чайник, если бы ты не написал про крым, я бы тупил сидел. чекни меняется ли айпишник, попробуй ребутнуть роутер+комп, хз даже блин(
> 
> алилуя, разобрался) спасибо, бро, за ответы :)

нез, удачи купить кейсиков)
