### ISSUE TITLE
error "go: could not create module cache: mkdir C:\Program Files\Go\pkg\mod: Access is denied."

### ISSUE THREAD

**Issue by SapigaL** [1makarov/binance-nft-buy#42]

**Comment by SapigaL** [comment]
помогите если кто-то сталкивался с такой проблемой, хотел запустить через 'sudo' как на линукс есть но у винды такой команды толком нету((

**Comment by 1makarov** [comment]
> помогите если кто-то сталкивался с такой проблемой, хотел запустить через 'sudo' как на линукс есть но у винды такой команды толком нету((

запусти cmd как администратор
