### ISSUE TITLE
Есть успехи на сегодняшнем дропе Dream Card Mystery Box II?

### ISSUE THREAD

**Issue by 1oneid** [1makarov/binance-nft-buy#44]
Есть успехи на сегодняшнем дропе Dream Card Mystery Box II? кто то что то взял этим ботом?

**Comment by Ivantesss** [comment]
![Uploading 1D255B53-0F59-4925-A636-49342B4BB726.png…]()

**Comment by izzgoy** [comment]
0/20

**Comment by Ivantesss** [comment]
Ебал я этот бинанс не реально ничего забрать уже 4 раздачи пошли в помойку

**Comment by izzgoy** [comment]
> Ебал я этот бинанс не реально ничего забрать уже 4 раздачи пошли в помойку

Пока что два сейла проебал

**Comment by Ivantesss** [comment]
> > Ебал я этот бинанс не реально ничего забрать уже 4 раздачи пошли в помойку
> 
> Пока что два сейла проебал

Забирал хоть что-то?

**Comment by izzgoy** [comment]
> > > Ебал я этот бинанс не реально ничего забрать уже 4 раздачи пошли в помойку
> > 
> > 
> > Пока что два сейла проебал
> 
> Забирал хоть что-то?
с ботом - нет

**Comment by LuckyFecher** [comment]
с ботом нет, на маркете ток
