### ISSUE TITLE
Как исправить? open .env: The system cannot find the file specified

### ISSUE THREAD

**Issue by tonymorrisoff** [1makarov/binance-nft-buy#46]
![file](https://user-images.githubusercontent.com/90840625/133604743-b1f73814-20f1-4c5c-91fa-356fb418668e.jpg)
Подскажите пожалуйста как исправить?

**Comment by izzgoy** [comment]
в каком формате ты сохранил файл .env?

**Comment by tonymorrisoff** [comment]
> в каком формате ты сохранил файл .env?

в env
![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)

**Comment by 1makarov** [comment]
> > в каком формате ты сохранил файл .env?
> 
> в env
> ![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)

по сути у тебя все верно, все равно не работает?

**Comment by tonymorrisoff** [comment]
> > > в каком формате ты сохранил файл .env?
> > 
> > 
> > в env
> > ![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)
> 
> по сути у тебя все верно, все равно не работает?

да,всё равно не работает

**Comment by 1makarov** [comment]
> > > > в каком формате ты сохранил файл .env?
> > > 
> > > 
> > > в env
> > > ![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)
> > 
> > 
> > по сути у тебя все верно, все равно не работает?
> 
> да,всё равно не работает

сделай скриншот папки с файлами, пожалуйста

**Comment by tonymorrisoff** [comment]
> > > > > в каком формате ты сохранил файл .env?
> > > > 
> > > > 
> > > > в env
> > > > ![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)
> > > 
> > > 
> > > по сути у тебя все верно, все равно не работает?
> > 
> > 
> > да,всё равно не работает
> 
> сделай скриншот папки с файлами, пожалуйста

![papka](https://user-images.githubusercontent.com/90840625/133642059-b123a6c4-b501-4a98-8d14-9fae46e971b4.jpg)

**Comment by 1makarov** [comment]
> > > > > > в каком формате ты сохранил файл .env?
> > > > > 
> > > > > 
> > > > > в env
> > > > > ![file env](https://user-images.githubusercontent.com/90840625/133608151-0b45ad6b-56c6-45c7-9bd9-f299d286ba93.jpg)
> > > > 
> > > > 
> > > > по сути у тебя все верно, все равно не работает?
> > > 
> > > 
> > > да,всё равно не работает
> > 
> > 
> > сделай скриншот папки с файлами, пожалуйста
> 
> ![papka](https://user-images.githubusercontent.com/90840625/133642059-b123a6c4-b501-4a98-8d14-9fae46e971b4.jpg)
> 
> не знаю что не так, мб я тупой и что то пропустил

Хм, все правильно, попробуй ещё раз пересоздать .env на исключительно английской раскладке, если не получится, вряд ли как-то смогу помочь :(
