### ISSUE TITLE
количество запросов

### ISSUE THREAD

**Issue by animetrider** [1makarov/binance-nft-buy#47]
Почему время между запросов было аж 3 секунды?
И ещё вопрос. Говорят что другие боты долбят по 1-2к запросов (не понял правда в секунду или за всё время чтобы купить) даже если в 3-4 секунды это же чудовищная разница между данным ботом и другими, может всё таки бан как-то обходится? как он вообще отображается? есть какая-то ошибка от бинанса конкретная?
![aa690212-e4a4-493c-9e8d-50c296bb5e09](https://user-images.githubusercontent.com/90841696/133610600-865709eb-9e2a-4089-b5b2-8c64baec0783.jpg)

**Comment by 1makarov** [comment]
Дело в том что бот не отправляет новый запрос, пока прошлый не завершиться. У конкурентов же, запросы летят спамом не дожидаясь завершения.

**Comment by animetrider** [comment]
> Дело в том что бот не отправляет новый запрос, пока прошлый не завершиться. У конкурентов же, запросы летят спамом не дожидаясь завершения. 

Почему нельзя попробовать сделать так же? И что скажешь по поводу банов(тех о которых ты говорил, на несколько сек типа) почему тогда они их не получают?

**Comment by 1makarov** [comment]
> > Дело в том что бот не отправляет новый запрос, пока прошлый не завершиться. У конкурентов же, запросы летят спамом не дожидаясь завершения.
> 
> Почему нельзя попробовать сделать так же? И что скажешь по поводу банов(тех о которых ты говорил, на несколько сек типа) почему тогда они их не получают?

получают

**Comment by animetrider** [comment]
> > > Дело в том что бот не отправляет новый запрос, пока прошлый не завершиться. У конкурентов же, запросы летят спамом не дожидаясь завершения.
> > 
> > Почему нельзя попробовать сделать так же? И что скажешь по поводу банов(тех о которых ты говорил, на несколько сек типа) почему тогда они их не получают?
> 
> получают

Подскажи тогда, пожалуйста какие параметры нужно изменить чтобы заставить твоего бота так же спамить?

**Comment by izzgoy** [comment]
и как настроить общее количество запросов и количество запросов в секунду?

**Comment by 1makarov** [comment]
> > > > Дело в том что бот не отправляет новый запрос, пока прошлый не завершиться. У конкурентов же, запросы летят спамом не дожидаясь завершения.
> > > 
> > > 
> > > Почему нельзя попробовать сделать так же? И что скажешь по поводу банов(тех о которых ты говорил, на несколько сек типа) почему тогда они их не получают?
> > 
> > 
> > получают
> 
> Подскажи тогда, пожалуйста какие параметры нужно изменить чтобы заставить твоего бота так же спамить?

добавить многопоточность

**Comment by 1makarov** [comment]
> и как настроить общее количество запросов и количество запросов в секунду?

на данный момент никак

**Comment by 1makarov** [comment]
скорее всего в дальнейшем добавлю функцию самостоятельной настройки многопоточности,задержки и тд

**Comment by animetrider** [comment]
> скорее всего в дальнейшем добавлю функцию самостоятельной настройки многопоточности,задержки и тд

Понял, спасибо за инфу, жду новой версии)
