### ISSUE TITLE
Запрос на покупку боксов с маркета

### ISSUE THREAD

**Issue by NeiTRoN96** [1makarov/binance-nft-buy#48]
Добрый день. А кто-нибудь может подсказать, покупка обычных боксов с маркета тоже идет через https://www.binance.com/bapi/nft/v1/private/nft/mystery-box/purchase ? Если в ручную покупаю, то показывает, что запрос https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-create , а потом https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-query . Но при order-create всегда приходит ответ "Network busy, please try again later". Кто-нибудь пробовал, может подсказать?

**Comment by JohnyInferno** [comment]
> Добрый день. А кто-нибудь может подсказать, покупка обычных боксов с маркета тоже идет через https://www.binance.com/bapi/nft/v1/private/nft/mystery-box/purchase ? Если в ручную покупаю, то показывает, что запрос https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-create , а потом https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-query . Но при order-create всегда приходит ответ "Network busy, please try again later". Кто-нибудь пробовал, может подсказать?

Тоже думаю, как реализовать. Перед order-create идет запрос на recaptcha, оттуда берется токен, который затем отправляется с запросом order-create (как я понял).

**Comment by NeiTRoN96** [comment]
Возможно и так. Но перед purchase тоже идет запрос на recaptcha. Однако по этому запросу нет проблем

**Comment by JohnyInferno** [comment]
> Возможно и так. Но перед purchase тоже идет запрос на recaptcha. Однако по этому запросу нет проблем

В headers у purchase есть параметр x-nft-checkbot-token? Этот параметр содержит значение, полученное от recaptcha.

**Comment by NeiTRoN96** [comment]
> > Возможно и так. Но перед purchase тоже идет запрос на recaptcha. Однако по этому запросу нет проблем
> 
> В headers у purchase есть параметр x-nft-checkbot-token? Этот параметр содержит значение, полученное от recaptcha.

Да, есть такое в заголовке. НО. Бот в заголовках такое не отправляет и покупка все равно совершается по обращению к  purchase

**Comment by JohnyInferno** [comment]
> > > Возможно и так. Но перед purchase тоже идет запрос на recaptcha. Однако по этому запросу нет проблем
> > 
> > 
> > В headers у purchase есть параметр x-nft-checkbot-token? Этот параметр содержит значение, полученное от recaptcha.
> 
> Да, есть такое в заголовке. НО. Бот в заголовках такое не отправляет и покупка все равно совершается по обращению к purchase

Тогда очень интересно получается, возможно дело и не в капче. Но в чем тогда? Пробовал также использовать Selenium для покупки, при нажатии кнопки ботом получал эту же ошибку "Network busy, please try again later". Хотя в обычном браузере все работает отлично.

**Comment by NeiTRoN96** [comment]
Да, непонятно. Да и описание ошибки вроде тоже говорит о том, что не из-за капчи. Если только разработчики не пошутили)

**Comment by JohnyInferno** [comment]
> Да, непонятно. Да и описание ошибки вроде тоже говорит о том, что не из-за капчи. Если только разработчики не пошутили)

Могу поделиться ссылкой на другого бота с гитхаба для изучения. Он написан на Java, в нем есть код с отправкой create-order запроса. Если нужно, пиши в тг @vitaliyfle

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md

**Comment by SlavaGolovatskyu** [comment]
> Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md

Данный бот все еще работает?

**Comment by hurmasik** [comment]
Кто нибудь решил данную проблему?

**Comment by IlyaPodprugin** [comment]
> Добрый день. А кто-нибудь может подсказать, покупка обычных боксов с маркета тоже идет через https://www.binance.com/bapi/nft/v1/private/nft/mystery-box/purchase ? Если в ручную покупаю, то показывает, что запрос https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-create , а потом https://www.binance.com/bapi/nft/v1/private/nft/nft-trade/order-query . Но при order-create всегда приходит ответ "Network busy, please try again later". Кто-нибудь пробовал, может подсказать?

Привет. 
Если не секрет, получилось как-то решить эту проблему?
Не могу никак найти ссылку, на которую отправлять запрос для покупки коллекций, а не мистери боксов
