### ISSUE TITLE
в чем заключается ошибка и как исправить

### ISSUE THREAD

**Issue by SamSeriousSam** [1makarov/binance-nft-buy#49]
Все настроено как положено, но вчера ошибку выдал , что якобы я не залогинен. Не подскажешь в чем проблема ? Спасибо ![image](https://user-images.githubusercontent.com/90501613/133715565-15761537-d0f3-4cb5-ae6f-e4819913c7dd.jpeg)

**Comment by 1makarov** [comment]
Привет, видимо ты перезашел в аккаунт, из-за этого введённые тобой куки стали невалидными.

**Comment by SamSeriousSam** [comment]
> Привет, видимо ты перезашел в аккаунт, из-за этого введённые тобой куки стали невалидными.

Спасибо, сегодня посмотрим как будет

**Comment by hnsik** [comment]
> > Привет, видимо ты перезашел в аккаунт, из-за этого введённые тобой куки стали невалидными.
> 
> Спасибо, сегодня посмотрим как будет

сегодня минусовый сейл мало кто в нем будет участвовать, так что ты точно возьмешь коробки
