### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AleksanderIkleiw** [1makarov/binance-nft-buy#51]
{'code': '000002', 'message': 'illegal parameter', 'messageDetail': None, 'data': None, 'success': False}

**Comment by ZlouNyan** [comment]
Фигово настроил .env файл
Кста дорогой разраб а у тебя на CORS построены запросы?

**Comment by 1makarov** [comment]
> {'code': '000002', 'message': 'illegal parameter', 'messageDetail': None, 'data': None, 'success': False}

Нужен скриншот
