### ISSUE TITLE
Заголовки в запросе самого бинанса 

### ISSUE THREAD

**Issue by nikital111** [1makarov/binance-nft-buy#52]
Тестил запрос через сам бинанс и увидел такие заголовки в хедере (x-nft-checkbot), может бинанс добавил че то, у тебя в коде вроде нет таких заголовков?

![Screenshot_7](https://user-images.githubusercontent.com/56406303/133892734-f71c7cf6-9950-438a-83dc-04ec6e8a0ba0.png)

**Comment by 1makarov** [comment]
Привет, но ведь это запрос на покупку нфт, нет?

**Comment by nikital111** [comment]
это запрос на покупку бокса Big Fat Sexy Mystery Box, брал один для теста руками

**Comment by 1makarov** [comment]
Перепроверил, вправду ввели капчу, спасибо

**Comment by Bohdanboiko** [comment]
Это было уже давно, как месяц точно, так что это не капча

**Comment by 1makarov** [comment]
> Это было уже давно, как месяц точно, так что это не капча

Если не капча, то что?

**Comment by DevArchi** [comment]
Есть идеи какие параметры в reload запрос каптчи передавать?
Я нашел такой проект по этой теме https://github.com/blaannk/Recaptcha-Invisible-Bypass
Но я так и не смог получить токен

**Comment by DevArchi** [comment]
> Есть идеи какие параметры в reload запрос каптчи передавать?
> Я нашел такой проект по этой теме https://github.com/blaannk/Recaptcha-Invisible-Bypass
> Но я так и не смог получить токен

@1makarov Скрипт в проекте рабочий, проверил руками. Выдает валидный токен рекаптчи.

**Comment by NeiTRoN96** [comment]
> > Есть идеи какие параметры в reload запрос каптчи передавать?
> > Я нашел такой проект по этой теме https://github.com/blaannk/Recaptcha-Invisible-Bypass
> > Но я так и не смог получить токен
> 
> @1makarov Скрипт в проекте рабочий, проверил руками. Выдает валидный токен рекаптчи.

А что ты использовал в качестве anchor?

**Comment by DevArchi** [comment]
> > > Есть идеи какие параметры в reload запрос каптчи передавать?
> > > Я нашел такой проект по этой теме https://github.com/blaannk/Recaptcha-Invisible-Bypass
> > > Но я так и не смог получить токен
> > 
> > 
> > @1makarov Скрипт в проекте рабочий, проверил руками. Выдает валидный токен рекаптчи.
> 
> А что ты использовал в качестве anchor?

При загрузке страницы с боксом выполняется запрос `https://www.recaptcha.net/recaptcha/api2/anchor?...`

**Comment by NeiTRoN96** [comment]
ну да. Там есть параметр в самом конце "cb", который каждый раз меняется. 
Если я просто копирую анкор, то у меня возвращается страница 404

**Comment by CheesySweasy** [comment]
> ну да. Там есть параметр в самом конце "cb", который каждый раз меняется.
> Если я просто копирую анкор, то у меня возвращается страница 404

Странно. Я скопировал "как есть" и выполнил GET запрос.
Параметр cb меняется, но на что влияет непонятно, поэтому я его оставил неизменным.

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md

**Comment by SundyHu** [comment]
https://github.com/cryptonw/binance_nft_bot/blob/main/README.md 404
