### ISSUE TITLE
Хоть у кого-то получилось забрать хоть один с последних 4 боксов используя этот бот?

### ISSUE THREAD

**Issue by skeenny** [1makarov/binance-nft-buy#54]

**Comment by keshinogattsu** [comment]
Не получилось, но бот работает. Дело в количестве запросов. Он ими не спамит в том количестве, которым спамят другие боты. Автор вроде писал что собирался добавить выбор количества запросов. Я бы даже скинулся на ускорение этого процесса, если он конечно хочет.

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md
