### ISSUE TITLE
Не работает ? 

### ISSUE THREAD

**Issue by Drotick** [1makarov/binance-nft-buy#56]
Я так понял уже все не работает бот ?

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md

**Comment by Dovban** [comment]
Hi, I have a bot that can bypass the captcha, it is one of the best on the market, contact me on Telegram. https://t.me/main_cypto_hub_2
