### ISSUE TITLE
У меня получилось!

### ISSUE THREAD

**Issue by Targan** [1makarov/binance-nft-buy#57]
Спасибо, бот отлично работает!
Если получиться заработать с меня пряники благодарности!)
![image](https://user-images.githubusercontent.com/9981995/134335073-373d69dc-7ddc-408b-a040-3dfbdfabae4d.png)

**Comment by Drotick** [comment]
![70D153BF-DC7D-44F0-A77A-65D7E8E21547](https://user-images.githubusercontent.com/91186498/134363564-6fd43d20-8fc8-43b5-bf27-92013074d26b.jpeg)
Почему у тебя так много запросов ? У меня вот прошлый бром не купило почему то :(

**Comment by Targan** [comment]
Потому что сверху сервера бинанса, а снизу сервер который я орендовал
пинг меньше, вот и запросов больше
![image](https://user-images.githubusercontent.com/9981995/134452901-aff1845d-a587-4398-baa5-14d34c85eeed.png)

**Comment by Targan** [comment]
А вот и НФТ с покерными картами купил
![image](https://user-images.githubusercontent.com/9981995/134496817-c7435d0f-ac71-4ee7-99bc-c833d1142d12.png)

**Comment by proxzi** [comment]
взял руками, бот не взял, бред

**Comment by provolk** [comment]
Боюсь плохой это знак, были бы боксы топовые - взять бы не получилось, а там конечно посмотрим...

**Comment by NeiTRoN96** [comment]
А что никто не продает их?

**Comment by Holodun406** [comment]
> А что никто не продает их?

Лок на 14 часов

**Comment by alerez** [comment]
![Снимок экрана 2021-09-23 в 14 07 38](https://user-images.githubusercontent.com/56561101/134503735-61da052e-e591-471d-9734-8e0066d87071.png)

Сколько такая карта может стоить?

**Comment by Nelegal1378** [comment]
Всем привет, есть бот-запросник с обходом капчи. По вопросам пишите в телегу - @godzila_bott. Всё покажу, расскажу с удовольствием

**Comment by dhaern** [comment]
> Всем привет, есть бот-запросник с обходом капчи. По вопросам пишите в телегу - @godzila_bott. Всё покажу, расскажу с удовольствием

Stfu cunt scammer

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md
