### ISSUE TITLE
Поддержите ребят

### ISSUE THREAD

**Issue by Dovban** [1makarov/binance-nft-buy#58]
Продавали действительно рабочий софт, их телегу снесли и они стараются развить новый канал. Всем зарание выражают благодарность. https://t.me/main_cypto_hub_2

**Comment by Nelegal1378** [comment]
Всем привет, есть бот-запросник с обходом капчи. По вопросам пишите в телегу - @godzila_bott. Всё покажу, расскажу с удовольствием

**Comment by 1makarov** [comment]
Перебор ребят.
