### ISSUE TITLE
Ошибка Network busy, please try again later

### ISSUE THREAD

**Issue by Juonior** [1makarov/binance-nft-buy#59]
Ребят, делаю запрос на покупку нфт на питоне. Выдает {"code":"10000222","message":"Network busy, please try again later","messageDetail":null,"data":null,"success":false}
Я так понимаю, что эт защита от ботов. Как решить?

**Comment by leadmanager05** [comment]
Вот нормально рабочий бот: https://github.com/cryptonw/binance_nft_bot/blob/main/README.md
