### ISSUE TITLE
Перестал покупать

### ISSUE THREAD

**Issue by Targan** [1makarov/binance-nft-buy#63]
Судя по всему, бинанс начал блокировать запросы или что то в этом роде
![image](https://user-images.githubusercontent.com/9981995/138048601-09e6eb63-8cfb-4059-a126-a31d3a1d2793.png)

**Comment by SlavaGolovatskyu** [comment]
> Автор, можно ли как то с вами связаться и пообщаться?

Че тут не понятного? Бинанс блокирует запросы. Зачем тебе автор? Он уже заебался отвечать таким как ты. Их милионы. То файл не создали то не авторизовались. Напиши своего бота и не еби мозги людям. Тебе бесплатно бота дали.

**Comment by podmost777** [comment]
> Автор, можно ли как то с вами связаться и пообщаться?

Здравствуйте! У вас получилось обойти эту ошибку? Если да, то как?

**Comment by podmost777** [comment]
> Судя по всему, бинанс начал блокировать запросы или что то в этом роде ![image](https://user-images.githubusercontent.com/9981995/138048601-09e6eb63-8cfb-4059-a126-a31d3a1d2793.png)

Здравствуйте! У вас получилось обойти эту ошибку? Если да, то как?

**Comment by foxymous** [comment]
> Судя по всему, бинанс начал блокировать запросы или что то в этом роде ![image](https://user-images.githubusercontent.com/9981995/138048601-09e6eb63-8cfb-4059-a126-a31d3a1d2793.png)

напиши в телегу дружище. @foxymous 
есть интересная тема для обсуждения совместного. отзовись крч
