### ISSUE TITLE
consultation

### ISSUE THREAD

**Issue by 1131683595** [1makarov/binance-nft-buy#65]
Hi bro,

I am from china. and I am interested in crypto. I saw your bot and I think your work is amazing.

I want to consult that if I want to code my own rush buy script of crypto, what course should I learn? and how long is the study period?

And can you give me you telegram account? I can consult you something by paying money or crypto in the telegram. And maybe we can do work together.

Thanks.

**Comment by Dovban** [comment]
Hi, I have a bot that can bypass the captcha, it is one of the best on the market, contact me on Telegram. https://t.me/main_cypto_hub_2
