### ISSUE TITLE
Привет Бро

### ISSUE THREAD

**Issue by getgleb** [1makarov/binance-nft-buy#66]
Не смог бы дать телегу, хотелось бы поговорить насчёт бота

**Comment by Bobchenko96** [comment]
> Не смог бы дать телегу, хотелось бы поговорить насчёт бота

Привет, я новичок совсем, но уже понятно и так, что без бота на бинансе никуда совсем.
У тебя есть какой-нибудь бот или инфа как прописать его?

**Comment by DmitrySidorow** [comment]
> > Не смог бы дать телегу, хотелось бы поговорить насчёт бота
> 
> Привет, я новичок совсем, но уже понятно и так, что без бота на бинансе никуда совсем. У тебя есть какой-нибудь бот или инфа как прописать его?

а может денег сразу на счет закинуть? пиши адрес btc
