### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by bardakk1** [1makarov/binance-nft-buy#9]
Извиняюсь, что создаю второй запрос, но 1makarov написал - "нужно настроить path golang"
Ошибка: - go: could not create module cache: mkdir C:\Users\Artyom\go: The system cannot find the path specified.
Информации в гугле просто не нашёл, можно подсказать где это можно настроить?

**Comment by 1makarov** [comment]
Привет ещё раз, с удовольствием бы подсказал, но сегодня убил около часа на данную ошибку и не смог помочь человеку. Вряд ли смогу дать какую-то подсказку, извини.

**Comment by bardakk1** [comment]
> Привет ещё раз, с удовольствием бы подсказал, но сегодня убил около часа на данную ошибку и не смог помочь человеку. Вряд ли смогу дать какую-то подсказку, извини.

Можно закрывать, решил проблему.

**Comment by cruzerio** [comment]
> > Привет ещё раз, с удовольствием бы подсказал, но сегодня убил около часа на данную ошибку и не смог помочь человеку. Вряд ли смогу дать какую-то подсказку, извини.
> 
> Можно закрывать, решил проблему.

Можно узнать как вы решили проблему?

**Comment by bardakk1** [comment]
> > > Привет ещё раз, с удовольствием бы подсказал, но сегодня убил около часа на данную ошибку и не смог помочь человеку. Вряд ли смогу дать какую-то подсказку, извини.
> > 
> > 
> > Можно закрывать, решил проблему.
> 
> Можно узнать как вы решили проблему?

Собственно посмотрел по этому пути - C:\Users\Artyom\go  - там был файл "go" но он был в неизвестном формате и пустой, я его удалил и заново попытался запустить программу и после того как я удалил и запустил у меня начали скачиваться директории и всё запустилось
